version: "3"
   
services:
  db:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=django_db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/steam
    ports:
      - "8000:8000"
    depends_on:
      - db
